name: FileSystem [Build]

env:
  JAVA_VERSION: 11
  DOTNET_VERSION: 6.0.x
  DOTNET_INCLUDE_PRERELEASE_VERSIONS: true
  DOTNET_BUILD_CONFIGURATION: Release
  SONAR_PATH: .\.sonar\scanner
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST: https://sonarcloud.io
  SONAR_ORGANIZATION: sharpgrip
  SONAR_PROJECT: SharpGrip_FileSystem
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: ${{ env.DOTNET_INCLUDE_PRERELEASE_VERSIONS }}

      - name: Install SonarCloud scanner
        shell: powershell
        run: |
          New-Item -Path ${{ env.SONAR_PATH }} -ItemType Directory -Force
          dotnet tool update dotnet-sonarscanner --tool-path ${{ env.SONAR_PATH }}

      - name: Build solution
        run: dotnet build -c ${{ env.DOTNET_BUILD_CONFIGURATION }} /warnaserror

      - name: Test solution
        run: dotnet test --no-build -c ${{ env.DOTNET_BUILD_CONFIGURATION }} --verbosity normal

      - name: Cleanup solution
        run: dotnet clean

      - name: Analyze solution
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORGANIZATION }}" /d:sonar.login="${{ env.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST }}"
          dotnet build -c ${{ env.DOTNET_BUILD_CONFIGURATION }}
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"